version: '3.8'
services:
  # Servis za PostgreSQL bazu podataka
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=iteh_baza
    ports:
      - '5432:5432'
    volumes:
      - podaciBaze:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d iteh_baza"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Servis za Next.js aplikaciju
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/iteh_baza?schema=public
      - JWT_SECRET=kljuc_za_jwt_token
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy

  # Servis za frontend (Vite + React)
  frontend:
    build:
      context: ./front/shop-scale-buddy
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - app

# Volumeni za trajno cuvanje podataka
volumes:
  podaciBaze: